# Generated by Django 3.0.4 on 2020-09-02 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField()),
                ('items', models.TextField()),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('summary', models.CharField(default='what the item is used for?', max_length=120)),
                ('phone', models.SmallIntegerField()),
                ('email', models.EmailField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('pub_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nimiss.Retail')),
            ],
        ),
    ]
